version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - pub_sub_network

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: 'PLAINTEXT://:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:9092'
      KAFKA_CREATE_TOPICS: "test-topic:1:1"
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - pub_sub_network

  mysql:
    image: mysql
    container_name: mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: "adminpwd"
      MYSQL_USER: "localuser"
      MYSQL_PASSWORD: "localpwd"
      MYSQL_DATABASE: "localdb"
    volumes:
      - ./data/kafka-poc/mysql:/var/lib/mysql
    networks:
      - pub_sub_network

  web:
    container_name: granular
    stdin_open: true
    tty: true
    build: ./../rest-app/
    image: granular:latest
    volumes:
      - ./../rest-app/:/app
      - ./../rest-app/app_configs/granular.conf:/etc/supervisor/conf.d/granular.conf
      - ./../rest-app/app_configs/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    command: '/usr/bin/supervisord'
    ports:
      - "8000:8000"
    networks:
      - pub_sub_network
    restart: always
    
networks:
  pub_sub_network:
    driver: bridge